[build]
    command = "npm run build"
    publish = "out"

[dev]
    command = "npm run dev"
    autoLaunch = false

[[redirects]]
    from = "https://pksmbketapang.netlify.app/*"
    to = "https://pksmbketapang.org/:splat"
    status = 301
    force = true

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[plugins]]
    package = "netlify-plugin-cache-nextjs"