[build]
    command = "cross-env ELEVENTY_ENV=prod npm run build"
    publish = "dist"

[dev]
    command = "npm start"
    autoLaunch = false

[[redirects]]
    from = "https://pksmbketapang.netlify.app/*"
    to = "https://pksmbketapang.org/:splat"
    status = 301
    force = true