# .github/workflows/main.yml

name: build harian
on:
  schedule:
    - cron: '0 5,11,17 * * *'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
